[[LibCHTTPClient]]
arch = "aarch64"
git-tree-sha1 = "e4b89e3bfd690fcaa0743b5d76c1599275fe032b"
os = "macos"

    [[LibCHTTPClient.download]]
    sha256 = "e04b21703138ab440c341cdbee542c02368e8be8651fffffb4f36b0485e7f3b3"
    url = "https://github.com/GlebZolotov/LibCHTTPClient_jll.jl/releases/download/LibCHTTPClient-v1.0.6+0/LibCHTTPClient.v1.0.6.aarch64-apple-darwin.tar.gz"
[[LibCHTTPClient]]
arch = "x86_64"
git-tree-sha1 = "c14198012b3ae3420bf1224448e0015fec2f6238"
os = "macos"

    [[LibCHTTPClient.download]]
    sha256 = "ed65ef8cd9d1b8bdfdf78fda57141d2f2da15426b4e67962f4ed04837d219a8d"
    url = "https://github.com/GlebZolotov/LibCHTTPClient_jll.jl/releases/download/LibCHTTPClient-v1.0.6+0/LibCHTTPClient.v1.0.6.x86_64-apple-darwin.tar.gz"
[[LibCHTTPClient]]
arch = "x86_64"
git-tree-sha1 = "694f1d967db2157b0bb5d9469bacb84758d5644d"
libc = "glibc"
os = "linux"

    [[LibCHTTPClient.download]]
    sha256 = "3e0e05f7572c1d593639459b7f67c18538b6169eb3e208ddfd91f097eda5b2f4"
    url = "https://github.com/GlebZolotov/LibCHTTPClient_jll.jl/releases/download/LibCHTTPClient-v1.0.6+0/LibCHTTPClient.v1.0.6.x86_64-linux-gnu.tar.gz"
