# Autogenerated wrapper script for LibCHTTPClient_jll for x86_64-apple-darwin
export lib_c_http_client

using LibCURL_jll
JLLWrappers.@generate_wrapper_header("LibCHTTPClient")
JLLWrappers.@declare_library_product(lib_c_http_client, "@rpath/http_client.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LibCURL_jll)
    JLLWrappers.@init_library_product(
        lib_c_http_client,
        "lib/http_client.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
